# Generated by Django 4.2.7 on 2025-12-20 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Student's full name", max_length=200)),
                ('roll_number', models.CharField(help_text='Unique roll number for the student', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Valid email address', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('course', models.CharField(help_text='Course name', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when student was added')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_date'],
            },
        ),
    ]
